# Generated by Django 4.1.1 on 2022-09-25 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dojo_ninjas_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dojo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dojo",
            name="desc",
            field=models.TextField(default="None"),
        ),
        migrations.AddField(
            model_name="dojo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ninja",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ninja",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dojo",
            name="state",
            field=models.CharField(max_length=2),
        ),
    ]
