# Generated by Django 4.1.1 on 2022-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books_authors_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
